In [1]:
import os

import pandas as pd
import numpy as np

In [2]:
file_one = "TADPOLE_D1_D2.csv"

In [3]:
file_one_df = pd.read_csv(file_one, encoding="ISO-8859-1")
file_one_df.head()

/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (471,473,474,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,569,570,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,599,601,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,624,625,626,627,628,629,630,631,632,633,634,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,723,724,725,726,727,728,729,730,731,732,733,734,735,736,737,738,739,745,746,748,749,750,751,752,753,754,755,756,757,758,759,760,761,762,763,764,765,766,767,770,771,776,777,778,779,780,781,782,783,784,785,786,787,788,789,790,791,794,795,797,798,799,800,801,802,803,804,806,807,808,809,810,811,812,813,814,815,816,817,818,819,820,821,822,823,824,825,826,827,828,829,830,831) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,RID,PTID,VISCODE,SITE,D1,D2,COLPROT,ORIGPROT,EXAMDATE,DX_bl,...,PHASE_UPENNBIOMK9_04_19_17,BATCH_UPENNBIOMK9_04_19_17,KIT_UPENNBIOMK9_04_19_17,STDS_UPENNBIOMK9_04_19_17,RUNDATE_UPENNBIOMK9_04_19_17,ABETA_UPENNBIOMK9_04_19_17,TAU_UPENNBIOMK9_04_19_17,PTAU_UPENNBIOMK9_04_19_17,COMMENT_UPENNBIOMK9_04_19_17,update_stamp_UPENNBIOMK9_04_19_17
0,2,011_S_0002,bl,11,1,1,ADNI1,ADNI1,2005-09-08,CN,...,,,,,,,,,,
1,3,011_S_0003,bl,11,1,0,ADNI1,ADNI1,2005-09-12,AD,...,ADNI1,UPENNBIOMK9,P06-MP02-MP01,P06-MP02-MP01/2,2016-12-14,741.5,239.7,22.83,NaN,2017-04-20 14:39:54.0
2,3,011_S_0003,m06,11,1,0,ADNI1,ADNI1,2006-03-13,AD,...,,,,,,,,,,
3,3,011_S_0003,m12,11,1,0,ADNI1,ADNI1,2006-09-12,AD,...,ADNI1,UPENNBIOMK9,P06-MP02-MP01,P06-MP02-MP01/2,2016-12-14,601.4,251.7,24.18,NaN,2017-04-20 14:39:54.0
4,3,011_S_0003,m24,11,1,0,ADNI1,ADNI1,2007-09-12,AD,...,,,,,,,,,,

In [4]:
selected_file_one = file_one_df.loc[:, ["PTID","DX","ADAS13", "Ventricles", "CDRSB", "ADAS11", "MMSE",  "RAVLT_immediate", "Hippocampus", "WholeBrain", "Entorhinal", "MidTemp", "FDG", "AV45", "ABETA_UPENNBIOMK9_04_19_17", "TAU_UPENNBIOMK9_04_19_17", "PTAU_UPENNBIOMK9_04_19_17", "APOE4", "AGE"]]
selected_file_one.head()

,PTID,DX,ADAS13,Ventricles,CDRSB,ADAS11,MMSE,RAVLT_immediate,Hippocampus,WholeBrain,Entorhinal,MidTemp,FDG,AV45,ABETA_UPENNBIOMK9_04_19_17,TAU_UPENNBIOMK9_04_19_17,PTAU_UPENNBIOMK9_04_19_17,APOE4,AGE
0,011_S_0002,NL,18.67,118233.0,0.0,10.67,28.0,44.0,8336.0,1229740.0,4177.0,27936.0,1.36926,NaN,,,,0.0,74.3
1,011_S_0003,Dementia,31.00,84599.0,4.5,22.00,20.0,22.0,5319.0,1129830.0,1791.0,18422.0,1.09079,NaN,741.5,239.7,22.83,1.0,81.3
2,011_S_0003,Dementia,30.00,88580.0,6.0,19.00,24.0,19.0,5446.0,1100060.0,2427.0,16972.0,1.06360,NaN,,,,1.0,81.3
3,011_S_0003,Dementia,35.00,90099.0,3.5,24.00,17.0,31.0,5157.0,1095640.0,1596.0,17330.0,1.10384,NaN,601.4,251.7,24.18,1.0,81.3
4,011_S_0003,Dementia,37.67,97420.0,8.0,25.67,19.0,23.0,5139.0,1088560.0,1175.0,16398.0,1.03871,NaN,,,,1.0,81.3

In [5]:
selected_file_one.to_csv("measures.csv", index=False, header=True)

In [6]:
unique = selected_file_one["DX"].unique()
unique

array(['NL', 'Dementia', 'MCI', 'NL to MCI', 'MCI to Dementia',
       'MCI to NL', 'Dementia to MCI', nan, 'NL to Dementia'],
      dtype=object)

In [18]:
selected_file_two = file_one_df.loc[:, ["PTID","PTGENDER","PTRACCAT","PTMARRY","PTEDUCAT", "DX","ADAS13", "Ventricles", "CDRSB", "ADAS11", "MMSE",  "RAVLT_immediate", "Hippocampus", "WholeBrain", "Entorhinal", "MidTemp", "FDG", "AV45", "ABETA_UPENNBIOMK9_04_19_17", "TAU_UPENNBIOMK9_04_19_17", "PTAU_UPENNBIOMK9_04_19_17", "APOE4", "AGE"]]
selected_file_two.head()

,PTID,PTGENDER,PTRACCAT,PTMARRY,PTEDUCAT,DX,ADAS13,Ventricles,CDRSB,ADAS11,...,WholeBrain,Entorhinal,MidTemp,FDG,AV45,ABETA_UPENNBIOMK9_04_19_17,TAU_UPENNBIOMK9_04_19_17,PTAU_UPENNBIOMK9_04_19_17,APOE4,AGE
0,011_S_0002,Male,White,Married,16,NL,18.67,118233.0,0.0,10.67,...,1229740.0,4177.0,27936.0,1.36926,NaN,,,,0.0,74.3
1,011_S_0003,Male,White,Married,18,Dementia,31.00,84599.0,4.5,22.00,...,1129830.0,1791.0,18422.0,1.09079,NaN,741.5,239.7,22.83,1.0,81.3
2,011_S_0003,Male,White,Married,18,Dementia,30.00,88580.0,6.0,19.00,...,1100060.0,2427.0,16972.0,1.06360,NaN,,,,1.0,81.3
3,011_S_0003,Male,White,Married,18,Dementia,35.00,90099.0,3.5,24.00,...,1095640.0,1596.0,17330.0,1.10384,NaN,601.4,251.7,24.18,1.0,81.3
4,011_S_0003,Male,White,Married,18,Dementia,37.67,97420.0,8.0,25.67,...,1088560.0,1175.0,16398.0,1.03871,NaN,,,,1.0,81.3

In [19]:
selected_file_two.to_csv("ptinfo.csv", index=False, header=True)

In [7]:
selected_file_one["DX"].value_counts()

MCI                3932
NL                 2668
Dementia           1732
MCI to Dementia     372
NL to MCI           108
MCI to NL            77
Dementia to MCI      12
NL to Dementia        3
Name: DX, dtype: int64

In [8]:
df = pd.DataFrame(
    selected_file_one
)
df.head()

,PTID,DX,ADAS13,Ventricles,CDRSB,ADAS11,MMSE,RAVLT_immediate,Hippocampus,WholeBrain,Entorhinal,MidTemp,FDG,AV45,ABETA_UPENNBIOMK9_04_19_17,TAU_UPENNBIOMK9_04_19_17,PTAU_UPENNBIOMK9_04_19_17,APOE4,AGE
0,011_S_0002,NL,18.67,118233.0,0.0,10.67,28.0,44.0,8336.0,1229740.0,4177.0,27936.0,1.36926,NaN,,,,0.0,74.3
1,011_S_0003,Dementia,31.00,84599.0,4.5,22.00,20.0,22.0,5319.0,1129830.0,1791.0,18422.0,1.09079,NaN,741.5,239.7,22.83,1.0,81.3
2,011_S_0003,Dementia,30.00,88580.0,6.0,19.00,24.0,19.0,5446.0,1100060.0,2427.0,16972.0,1.06360,NaN,,,,1.0,81.3
3,011_S_0003,Dementia,35.00,90099.0,3.5,24.00,17.0,31.0,5157.0,1095640.0,1596.0,17330.0,1.10384,NaN,601.4,251.7,24.18,1.0,81.3
4,011_S_0003,Dementia,37.67,97420.0,8.0,25.67,19.0,23.0,5139.0,1088560.0,1175.0,16398.0,1.03871,NaN,,,,1.0,81.3

In [9]:
def V_pct_change(df):
    df['V_pct'] = 100 * (1 - df.iloc[0].Ventricles / df.Ventricles)
    return df

df=df.groupby('PTID').apply(V_pct_change)

In [10]:
df.head()

,PTID,DX,ADAS13,Ventricles,CDRSB,ADAS11,MMSE,RAVLT_immediate,Hippocampus,WholeBrain,Entorhinal,MidTemp,FDG,AV45,ABETA_UPENNBIOMK9_04_19_17,TAU_UPENNBIOMK9_04_19_17,PTAU_UPENNBIOMK9_04_19_17,APOE4,AGE,V_pct
0,011_S_0002,NL,18.67,118233.0,0.0,10.67,28.0,44.0,8336.0,1229740.0,4177.0,27936.0,1.36926,NaN,,,,0.0,74.3,0.000000
1,011_S_0003,Dementia,31.00,84599.0,4.5,22.00,20.0,22.0,5319.0,1129830.0,1791.0,18422.0,1.09079,NaN,741.5,239.7,22.83,1.0,81.3,0.000000
2,011_S_0003,Dementia,30.00,88580.0,6.0,19.00,24.0,19.0,5446.0,1100060.0,2427.0,16972.0,1.06360,NaN,,,,1.0,81.3,4.494242
3,011_S_0003,Dementia,35.00,90099.0,3.5,24.00,17.0,31.0,5157.0,1095640.0,1596.0,17330.0,1.10384,NaN,601.4,251.7,24.18,1.0,81.3,6.104396
4,011_S_0003,Dementia,37.67,97420.0,8.0,25.67,19.0,23.0,5139.0,1088560.0,1175.0,16398.0,1.03871,NaN,,,,1.0,81.3,13.160542

In [11]:
df.loc[df["PTID"] == "023_S_0042"].head()

,PTID,DX,ADAS13,Ventricles,CDRSB,ADAS11,MMSE,RAVLT_immediate,Hippocampus,WholeBrain,Entorhinal,MidTemp,FDG,AV45,ABETA_UPENNBIOMK9_04_19_17,TAU_UPENNBIOMK9_04_19_17,PTAU_UPENNBIOMK9_04_19_17,APOE4,AGE,V_pct
84,023_S_0042,MCI,12.00,48933.0,0.5,7.00,30.0,29.0,4087.0,952780.0,2784.0,16009.0,NaN,NaN,1258,250.1,18.23,0.0,72.8,0.000000
85,023_S_0042,MCI,9.67,51056.0,1.0,4.67,28.0,22.0,3793.0,938210.0,2131.0,15782.0,NaN,NaN,,,,0.0,72.8,4.158179
86,023_S_0042,MCI to Dementia,15.00,52933.0,2.0,11.00,24.0,30.0,3858.0,920277.0,2773.0,15444.0,NaN,NaN,766.5,205.4,18.4,0.0,72.8,7.556723
87,023_S_0042,Dementia,20.67,53443.0,2.0,11.67,21.0,28.0,3607.0,926228.0,1825.0,15893.0,NaN,NaN,,,,0.0,72.8,8.438898
88,023_S_0042,Dementia,18.33,55895.0,3.0,9.33,22.0,25.0,3471.0,924895.0,2346.0,16940.0,NaN,NaN,1224,208.7,18.44,0.0,72.8,12.455497

In [12]:
def H_pct_change(df):
    df['H_pct'] = 100 * (1 - df.iloc[0].Hippocampus / df.Hippocampus)
    return df

df=df.groupby('PTID').apply(H_pct_change)
df.head()

,PTID,DX,ADAS13,Ventricles,CDRSB,ADAS11,MMSE,RAVLT_immediate,Hippocampus,WholeBrain,...,MidTemp,FDG,AV45,ABETA_UPENNBIOMK9_04_19_17,TAU_UPENNBIOMK9_04_19_17,PTAU_UPENNBIOMK9_04_19_17,APOE4,AGE,V_pct,H_pct
0,011_S_0002,NL,18.67,118233.0,0.0,10.67,28.0,44.0,8336.0,1229740.0,...,27936.0,1.36926,NaN,,,,0.0,74.3,0.000000,0.000000
1,011_S_0003,Dementia,31.00,84599.0,4.5,22.00,20.0,22.0,5319.0,1129830.0,...,18422.0,1.09079,NaN,741.5,239.7,22.83,1.0,81.3,0.000000,0.000000
2,011_S_0003,Dementia,30.00,88580.0,6.0,19.00,24.0,19.0,5446.0,1100060.0,...,16972.0,1.06360,NaN,,,,1.0,81.3,4.494242,2.331987
3,011_S_0003,Dementia,35.00,90099.0,3.5,24.00,17.0,31.0,5157.0,1095640.0,...,17330.0,1.10384,NaN,601.4,251.7,24.18,1.0,81.3,6.104396,-3.141361
4,011_S_0003,Dementia,37.67,97420.0,8.0,25.67,19.0,23.0,5139.0,1088560.0,...,16398.0,1.03871,NaN,,,,1.0,81.3,13.160542,-3.502627

In [13]:
def Wb_pct_change(df):
    df['Wb_pct'] = 100 * (1 - df.iloc[0].WholeBrain / df.WholeBrain)
    return df

df=df.groupby('PTID').apply(Wb_pct_change)
df.head()

,PTID,DX,ADAS13,Ventricles,CDRSB,ADAS11,MMSE,RAVLT_immediate,Hippocampus,WholeBrain,...,FDG,AV45,ABETA_UPENNBIOMK9_04_19_17,TAU_UPENNBIOMK9_04_19_17,PTAU_UPENNBIOMK9_04_19_17,APOE4,AGE,V_pct,H_pct,Wb_pct
0,011_S_0002,NL,18.67,118233.0,0.0,10.67,28.0,44.0,8336.0,1229740.0,...,1.36926,NaN,,,,0.0,74.3,0.000000,0.000000,0.000000
1,011_S_0003,Dementia,31.00,84599.0,4.5,22.00,20.0,22.0,5319.0,1129830.0,...,1.09079,NaN,741.5,239.7,22.83,1.0,81.3,0.000000,0.000000,0.000000
2,011_S_0003,Dementia,30.00,88580.0,6.0,19.00,24.0,19.0,5446.0,1100060.0,...,1.06360,NaN,,,,1.0,81.3,4.494242,2.331987,-2.706216
3,011_S_0003,Dementia,35.00,90099.0,3.5,24.00,17.0,31.0,5157.0,1095640.0,...,1.10384,NaN,601.4,251.7,24.18,1.0,81.3,6.104396,-3.141361,-3.120551
4,011_S_0003,Dementia,37.67,97420.0,8.0,25.67,19.0,23.0,5139.0,1088560.0,...,1.03871,NaN,,,,1.0,81.3,13.160542,-3.502627,-3.791247

In [15]:
def E_pct_change(df):
    df['E_pct'] = 100 * (1 - df.iloc[0].Entorhinal / df.Entorhinal)
    return df

df=df.groupby('PTID').apply(E_pct_change)
df.head()

,PTID,DX,ADAS13,Ventricles,CDRSB,ADAS11,MMSE,RAVLT_immediate,Hippocampus,WholeBrain,...,AV45,ABETA_UPENNBIOMK9_04_19_17,TAU_UPENNBIOMK9_04_19_17,PTAU_UPENNBIOMK9_04_19_17,APOE4,AGE,V_pct,H_pct,Wb_pct,E_pct
0,011_S_0002,NL,18.67,118233.0,0.0,10.67,28.0,44.0,8336.0,1229740.0,...,NaN,,,,0.0,74.3,0.000000,0.000000,0.000000,0.000000
1,011_S_0003,Dementia,31.00,84599.0,4.5,22.00,20.0,22.0,5319.0,1129830.0,...,NaN,741.5,239.7,22.83,1.0,81.3,0.000000,0.000000,0.000000,0.000000
2,011_S_0003,Dementia,30.00,88580.0,6.0,19.00,24.0,19.0,5446.0,1100060.0,...,NaN,,,,1.0,81.3,4.494242,2.331987,-2.706216,26.205192
3,011_S_0003,Dementia,35.00,90099.0,3.5,24.00,17.0,31.0,5157.0,1095640.0,...,NaN,601.4,251.7,24.18,1.0,81.3,6.104396,-3.141361,-3.120551,-12.218045
4,011_S_0003,Dementia,37.67,97420.0,8.0,25.67,19.0,23.0,5139.0,1088560.0,...,NaN,,,,1.0,81.3,13.160542,-3.502627,-3.791247,-52.425532

In [16]:
def Mt_pct_change(df):
    df['Mt_pct'] = 100 * (1 - df.iloc[0].MidTemp / df.MidTemp)
    return df

df=df.groupby('PTID').apply(Mt_pct_change)
df.head()

,PTID,DX,ADAS13,Ventricles,CDRSB,ADAS11,MMSE,RAVLT_immediate,Hippocampus,WholeBrain,...,ABETA_UPENNBIOMK9_04_19_17,TAU_UPENNBIOMK9_04_19_17,PTAU_UPENNBIOMK9_04_19_17,APOE4,AGE,V_pct,H_pct,Wb_pct,E_pct,Mt_pct
0,011_S_0002,NL,18.67,118233.0,0.0,10.67,28.0,44.0,8336.0,1229740.0,...,,,,0.0,74.3,0.000000,0.000000,0.000000,0.000000,0.000000
1,011_S_0003,Dementia,31.00,84599.0,4.5,22.00,20.0,22.0,5319.0,1129830.0,...,741.5,239.7,22.83,1.0,81.3,0.000000,0.000000,0.000000,0.000000,0.000000
2,011_S_0003,Dementia,30.00,88580.0,6.0,19.00,24.0,19.0,5446.0,1100060.0,...,,,,1.0,81.3,4.494242,2.331987,-2.706216,26.205192,-8.543483
3,011_S_0003,Dementia,35.00,90099.0,3.5,24.00,17.0,31.0,5157.0,1095640.0,...,601.4,251.7,24.18,1.0,81.3,6.104396,-3.141361,-3.120551,-12.218045,-6.301212
4,011_S_0003,Dementia,37.67,97420.0,8.0,25.67,19.0,23.0,5139.0,1088560.0,...,,,,1.0,81.3,13.160542,-3.502627,-3.791247,-52.425532,-12.342969

In [17]:
df.to_csv("pct_changes.csv", index=False, header=True)